version: "2"
services:
  nginx:
    build: ./nginx/
    ports:
    - "80:80"
    links:
    - app 
  app:
    container_name: app
    restart: always
    build: ./backend/
    ports:
      - "3017:3017"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
